
#################################
###  Author : Ross Searle         
###  Date : Wed Oct 07 09:57:32 2020                      
###  Project : TERN Landscapes
###  Purpose : Mucking around to work a processess to implement the pedotransfers for AWC generated by Sanji
#################################

library(raster)
library(stringr)
library(rgdal)
library(tictoc)

machineName <- as.character(Sys.info()['nodename'])

if(machineName=='TERNSOIL2'){
  malRoot <- '//fs1-cbr.nexus.csiro.au/{af-tern-mal-deb}/work/projects/ternlandscapes_2019/soiltexture/predictions/tiles'
  slgaRoot <- '//fs1-cbr.nexus.csiro.au/{af-digiscapesm}/work/External/National_digital_soil_property_maps'
  outRoot <- ''
}else{
  malRoot <- '/datasets/work/af-tern-mal-deb/work/projects/ternlandscapes_2019/soiltexture/predictions/tiles'
  slgaRoot <- '/datasets/work/af-digiscapesm/work/External/National_digital_soil_property_maps'
  outRoot <- '/scratch1/sea084/SLGA/AWC'
}

tic()
args = commandArgs(trailingOnly=TRUE)
k = as.numeric(args[1])
#k=153
print(paste0("Processing iteraration = ", k))

root.tiles <-  paste0(malRoot)
source.dirs <- list.files(path = root.tiles, full.names = T)

slgaD <- c('000_005','005_015','015_030','030_060','060_100','100_200')

tilePath <- source.dirs[k]
print(tilePath)
tileNum <- basename(tilePath)
print(paste0('debug - ', tileNum))
outPath <- paste0(outRoot, '/',tileNum)
if(!dir.exists(outPath)){dir.create(outPath)}
                  
for (i in 1:6) {
  print(paste0('Generating depth layer ', i))
  
  fdul <- paste0(outPath, '/DUL_', i, '.tif')
  fdll <- paste0(outPath, '/DLL_', i, '.tif')
  if(!file.exists(fdul)|!file.exists(fdll)) {
  r1Path <- paste0(malRoot,'/', tileNum, '/pred_clay_mean_d', i, '.tif' )
  print(r1Path)
  tClay <-  raster(r1Path)
  tSand <-  raster(paste0(malRoot,'/', tileNum, '/pred_sand_mean_d', i, '.tif' ))
  tSilt <-  raster(paste0(malRoot,'/', tileNum, '/pred_silt_compos_mean_d', i, '.tif' ))
  bd <- raster(paste0(slgaRoot,'/Bulk-Density/BDW_',slgaD[[i]] ,'_EV_N_P_AU_NAT_C_20140801.tif' ))
  oc <- raster(paste0(slgaRoot,'/SOC/SOC_',slgaD[[i]] ,'_EV_N_P_AU_NAT_C_20140801.tif' ))
  
  tbd <- crop(bd, tClay)
  toc <- crop(oc, tClay)

  Vol.DUL=48.98-(21.86*tbd)+(0.36*tClay)-(0.06*tSand)-(0.19*sqrt(tSilt))+(2.90*sqrt(toc))
  Vol.DLL=17.40-(10.05*tbd)+(0.34*tClay)-(0.02*tSand)+(0.18*tSilt)
  
  writeRaster(Vol.DUL, fdul)
  writeRaster(Vol.DLL, fdll)
  
  }else{
    print("Files exist")
  }
    
}

print(paste0('Finished Successfully'))

