
#################################
###  Author : Ross Searle         
###  Date : Wed Oct 07 09:57:32 2020                      
###  Project : TERN Landscapes
###  Purpose : Mucking around to work a processess to implement the pedotransfers for AWC generated by Sanji
#################################

library(raster)
library(stringr)
library(rgdal)




slgaPath <- '//fs1-cbr.nexus.csiro.au/{af-digiscapesm}/work/External/National_digital_soil_property_maps'
textPath <- '//fs1-cbr.nexus.csiro.au/{af-tern-mal-deb}/work/projects/ternlandscapes_2019/soiltexture/predictions/tiles/3440'
outRoot <- '//gpfs2-cbr.san.csiro.au/lw_rowra_work/3_Land_suitability/0_Working/Ross/National_AWC'

slgaD <- c('000_005','005_015','015_030','030_060','060_100','100_200')

for (i in 1:6) {

  tClay <-  raster(paste0(textPath,'/pred_clay_mean_d', i, '.tif' ))
  tSand <-  raster(paste0(textPath,'/pred_sand_mean_d', i, '.tif' ))
  tSilt <-  raster(paste0(textPath,'/pred_silt_compos_mean_d', i, '.tif' ))
  bd <- raster(paste0(slgaPath,'/Bulk-Density/BDW_',slgaD[[i]] ,'_EV_N_P_AU_NAT_C_20140801.tif' ))
  oc <- raster(paste0(slgaPath,'/SOC/SOC_',slgaD[[i]] ,'_EV_N_P_AU_NAT_C_20140801.tif' ))
  
  tbd <- crop(bd, tClay)
  toc <- crop(oc, tClay)
  
  
  plot(r)
  
  Vol.DUL=48.98-(21.86*tbd)+(0.36*tClay)-(0.06*tSand)-(0.19*sqrt(tSilt))+(2.90*sqrt(toc))
  Vol.DLL=17.40-(10.05*tbd)+(0.34*tClay)-(0.02*tSand)+(0.18*tSilt)
  
  writeRaster()
  
    
}



tClay <-  raster(paste0(textPath,'/pred_clay_mean_d1.tif' ))
tSand <-  raster(paste0(textPath,'/pred_sand_mean_d1.tif' ))
tSilt <-  raster(paste0(textPath,'/pred_silt_compos_mean_d1.tif' ))
bd <- raster(paste0(slgaPath,'/Bulk-Density/BDW_000_005_EV_N_P_AU_NAT_C_20140801.tif' ))
oc <- raster(paste0(slgaPath,'/SOC/SOC_000_005_EV_N_P_AU_NAT_C_20140801.tif' ))

tbd <- crop(bd, tClay)
toc <- crop(oc, tClay)


plot(r)

Vol.DUL=48.98-(21.86*tbd)+(0.36*tClay)-(0.06*tSand)-(0.19*sqrt(tSilt))+(2.90*sqrt(toc))
Vol.DLL=17.40-(10.05*tbd)+(0.34*tClay)-(0.02*tSand)+(0.18*tSilt)
